### ISSUE TITLE
expose wallclock time?

### ISSUE THREAD

**Issue by ltalirz** [nanotech-empa/aiidalab-empa-surfaces#1]
If I understand correctly, the walltime for the different steps is currently hardcoded.
https://github.com/cpignedoli/mc-empa-surfaces/blob/b49ae23ab13fbddce28d5fe459ec89cf1e5dc3a1/nanoribbon/nanoribbonwork.py#L46-L63
(when no wallclock is provided, it's 24h).
Would it make sense to expose this as a parameter of the workchain?

The thing is, if you want to demo the nanoribbon workflow on a small system, the job probably spends unnecessarily long in the queue.
I'm open to other solutions to the problem, let me know what you prefer.

**Comment by oschuett** [comment]
I would definitely **not** expose the walltime as a user parameter, because it can be very well predicted heuristically takings into account the structure size, thresholds, etc. These heuristics are exactly the kind of expert knowledge that should be encode in the workflows.

Furthermore, before we introduce user parameters we should always ask ourself if an experimentalist would be able to provide an answer.

The heuristics we currently have in the nanoribbon workflow are calibrated for Piz Daint. In order to generalize this I propose we write an app for running QE benchmarks on a given computer and store the results in its extra attributes. Then each workflow can take these performance measurements into account when estimating the walltime and number of nodes.

What do you think?

**Comment by ltalirz** [comment]
If done well, I think this would be an extremely valuable app.

There are different QE benchmark sets available
http://qe-forge.org/gf/project/q-e/frs/?action=FrsReleaseBrowse&frs_package_id=36

I started playing around with the 'small' benchmark, but I'll have to continue later (opening a text file on daint can take minutes at the moment...).

One can comment the first few lines of the scripts where you configure the benchmark and provide it via environment variables like so
```
#!/bin/bash

#SBATCH --no-requeue
#SBATCH --job-name="qe-bench"
#SBATCH --get-user-env
#SBATCH --output=_scheduler-stdout.txt
#SBATCH --error=_scheduler-stderr.txt
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=12
#SBATCH --time=00:10:00


### computer prepend_text start ###
#SBATCH --account=s746
#SBATCH --constraint=gpu
##SBATCH --cpus-per-task=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=normal
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
source $MODULESHOME/init/bash
module load daint-gpu
ulimit -s unlimited
export CRAY_CUDA_MPS=1
### computer prepend_text end ###


### code prepend_text start ###
module load QuantumESPRESSO/6.1.0-CrayIntel-17.08
### code prepend_text end ###

export ARCH="Piz Daint"
export EXE=pw.x
export SCRATCH_DIR=./
export mpi_cmd='srun -n 24'
export ncpu_min=2
export ncpu_min=24
export increment=2

source pwscf_bench.sh

source para-speedup.sh
```

**Comment by oschuett** [comment]
I'm glad you like the benchmarking approach. Ideally, they should be run through AiiDA for portability (and documentation) reasons.

**Comment by edditler** [comment]
Another way would be to provide an input field in the notebook which is prefilled with the suggested value, giving the user the choice to set the value themselves (if they know what they are doing) or to stick to the provided value.
We are now doing the same for the number of nodes used for the Slab geometry optimization.

**Comment by cpignedoli** [comment]
I am open to discuss this also on monday.
We have to be careful that, in the specific case of the nanoribbon workflow
some sections (teh first cell opt and the KS plotting) 
require a walltime not easily accessible to a user.

**Comment by ltalirz** [comment]
I agree with Ole that if a workflow is aimed at experimentalists, then only the settings that are relevant & understandable to the experimentalist should be exposed.

Still, I think there is no harm in having e.g. a second user interface to the workflow intended for theorists that exposes more settings (or, if one prefers, a new workflow that reuses parts of the original one).

With respect to the automatic benchmarking, I was just made aware of an interesting recent effort for QE in this respect and I suggest we wait with implementing this until I have some more news.

**Comment by yakutovicha** [comment]
as far as I am aware, it is now possible to specify the maximum run time. So I close the issue.
