### ISSUE TITLE
NEB wfn restart issue

### ISSUE THREAD

**Issue by dpasserone** [nanotech-empa/aiidalab-empa-surfaces#165]
The present implementation of the NEB app (Reactions, ./apps/surfaces/submit_reactions.ipynb ) has a bug. 
Since in the resulting input file aiida.inp the following line is present:

`      RESTART_FILE_NAME ./aiida-RESTART.wfn`

The individual replicas (e.g., Replica 7) will always look for a file called "**aiida-RESTART.wfn**" and NOT for the correct file "**aiida-BAND7-RESTART.wfn**". 

Since the former does not exist, the replica will always start from atomic guess at each step during the NEB optimization. This is not convenient. 

If the **RESTART_FILE_NAME** line is commented out, the correct restarts of the wfn are read (even at the first step, if present, but for sure at the following steps). 

Please fix @cpignedoli  @yakutovicha 

Thank you in advance, Daniele

**Comment by cpignedoli** [comment]
Thanks a lot @dpasserone for the bug report. I will take care fixing it.
