### ISSUE TITLE
NEB with ROTATE FRAMES issue

### ISSUE THREAD

**Issue by dpasserone** [nanotech-empa/aiidalab-empa-surfaces#167]
Dear developers

In the input file of the NEB app, (tested for slab systems), 

`ALIGN_FRAMES .FALSE.`

is specified. 
But since 

`ROTATE_FRAMES .FALSE.` is not specified, and the default is `.TRUE.`, 
the fixed atoms of the replica after the first, EVEN IF IDENTICAL ACROSS ALL REPLICA, are slightly moved. 
This is inconvenient. 

Please fix by adding
`ROTATE_FRAMES .FALSE. `

@cpignedoli @yakutovicha 

Thanks!

**Comment by cpignedoli** [comment]
thanks a lot @dpasserone, good catch, I will fix it

**Comment by yakutovicha** [comment]
fixed by #174
