### ISSUE TITLE
.export_structure in NEB bug

### ISSUE THREAD

**Issue by ramador09** [nanotech-empa/aiidalab-empa-surfaces#175]
When clicking `View & export` in a NEB, I'm met with the following error:
<img width="664" alt="Bildschirmfoto 2023-08-08 um 14 57 44" src="https://github.com/nanotech-empa/aiidalab-empa-surfaces/assets/106821034/d1c206e3-09a8-4b89-b489-cf3273b1d35f">

```python
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_3023380/2152644956.py in <cell line: 1>()
----> 1 pk = urlparse.parse_qs(urlparse.urlsplit(jupyter_notebook_url).query)['pk'][0]
      2 display(EmpaStructureViewer(structure=load_node(pk=int(pk))))

KeyError: 'pk'
```

My apps are completely updated it seems also.

**Comment by yakutovicha** [comment]
fixed in https://github.com/nanotech-empa/aiidalab-empa-surfaces/pull/163
