### ISSUE TITLE
Field for the  workchain descirption

### ISSUE THREAD

**Issue by cpignedoli** [nanotech-empa/aiidalab-empa-surfaces#182]
The field is now duplicated: "Process description:" on top and "Workflow description" below the "Submit" button
![image (2)](https://github.com/nanotech-empa/aiidalab-empa-surfaces/assets/22955065/ce82fa78-f65a-4722-891f-57ea23d99699)

**Comment by yakutovicha** [comment]
I assume this is a "reactions" app, a replica chain simulation, right?

**Comment by yakutovicha** [comment]
@cpignedoli, I am not able to reproduce this issue. Can you please provide more details? Which notebook is that? Are you sure you have the up-to-date version of the app?

**Comment by cpignedoli** [comment]
Everything seems to work
