### ISSUE TITLE
Improve the try except

### ISSUE THREAD

**Issue by cpignedoli** [nanotech-empa/aiidalab-empa-surfaces#82]
https://github.com/nanotech-empa/aiidalab-empa-surfaces/blob/d74ac695bc8abe6eb7b2535bd08ac694be8d0606/widgets/search_completed_widget.py#L180

if there is a broken link (e.g. a failed calculation removed) the link to subsequent successful calculations will be missing because of the except

**Comment by yakutovicha** [comment]
@cpignedoli can you double-check and confirm that it is still there?

**Comment by cpignedoli** [comment]
not sure it is still a problem we should check how the code was before the issue was opened

**Comment by yakutovicha** [comment]
The issue can be closed as the SPM app is merged into the aiidalab-empa-surfaces repo.
