### ISSUE TITLE
Accessing the "Inspecting aiida processes" page

### ISSUE THREAD

**Issue by dpasserone** [nanotech-empa/aiidalab-empa-surfaces#86]
Dear developers, in the Graphene Nanoribbon app, in the database you could access the "Inspect aiida processes" page by clicking on the left on the PK

![image](https://user-images.githubusercontent.com/45152275/149922396-152c7b12-8de5-4146-9f05-4e8142c2352d.png)

At present, this does not work (404 not found, thanks @eimrek for pointing it out).

However, in the Slab app, the optimized slab list does not have this possibility, and one has to note the PK and go back to the "Process list" and open the page from there.

![image](https://user-images.githubusercontent.com/45152275/149922572-cad41509-b587-4514-ad06-a78c5e98ed76.png)

Can you fix those two issues?

Thank you Daniele

**Comment by eimrek** [comment]
In the graphene nanoribbon app, you mean clicking on the PK number on the left, right? For me, it links to `aiida/aiida_graph_browser.ipynb`, which doesn't exist. So this needs to be fixed as well.

**Comment by dpasserone** [comment]
I meant clicking on the right on "show". There it works. Indeed, on the left on the PK it does not work, and yes, it needs to be fixed as well.

**Comment by eimrek** [comment]
The right "Show" link goes to the showing the band structure, KS orbitals, spin density etc, not into the process inspection. Am i missing something?

**Comment by dpasserone** [comment]
Ha, you are right. I was confused by my tabs. I will edit the Issue now.

**Comment by yakutovicha** [comment]
The issue for the nanoribbons app should be fixed in https://github.com/nanotech-empa/aiidalab-empa-nanoribbons/pull/52, while #110 should fix the issue for the surfaces app.
