### ISSUE TITLE
app for GW without GW-IC

### ISSUE THREAD

**Issue by cpignedoli** [nanotech-empa/aiidalab-empa-surfaces#97]
what if I do not have a GW-IC calculatiosn and I still want to plot the SCF and the GW levels as I am doing in this branch?

https://github.com/nanotech-empa/aiidalab-empa-surfaces/blob/98eb62c1ca2a34a062863e3000ce88ba405d9231/gw/postprocess.py#L17

**Comment by yakutovicha** [comment]
@cpignedoli I guess this is done already. Please close the issue if it is so.

**Comment by cpignedoli** [comment]
the GW app take scare of this
